version: 0.2

phases:
  install:
    commands:
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "Starting validation..."

  build:
    commands:
      - sam validate --template-file devops/template.yaml
      - sam build --template-file devops/template.yaml

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - .aws-sam/build/**/*