version: 0.2

phases:
  install:
    commands:
      - pip install aws-sam-cli

  build:
    commands:
      - sam validate --template-file devops/template.yaml
      - sam build  --template-file devops/template.yaml

artifacts:
  files:
    - '**/*'